### ISSUE TITLE
How to write to multiple paths? Swift

### ISSUE THREAD

**Issue by bibscy** [mownier/pyrobase#4]
Hi, I am trying to perform a multi-path write using the Firebase REST API, but I can't get it working. 
Could you please have a look at my question? https://stackoverflow.com/questions/46100421 . I cannot see this feature in the library you created. Many thanks

**Comment by mownier** [comment]
```swift
pyrobase.patch(path:"", value:["path/to/update1":"data1", "path/to/update2":"data2"]) { ... }
```

Here, the root path, which is `https://foo.firebaseio.com/.json`, is updated by the patch request. The keys in the `value` parameter will be the different locations/paths in the firebase realtime db.
